-   id: update-zola-post-updated-date
    name: update-zola-post-updated-date
    description: update-zola-post-updated-date
    entry: hook/update-zola-post-updated-date/update_zola_post_updated_date.sh
    language: script
    files: \.md$
    exclude: ^(README|_index)\.md$
