-   id: update-zola-post-updated-date
    name: update-zola-post-updated-date
    description: This hook adds or updates the "updated = YYYY-MM-DD" metadata of a staged .md file based on its modification date.
    entry: hook/update-zola-post-updated-date/update-zola-post-updated-date.sh
    language: script
    files: \.md$
    exclude: ^(README|_index)\.md$
